### ISSUE TITLE
Настроить Github actions

### ISSUE THREAD

**Issue by askarsyzdykov** [sozdik-kz/sozdik-android#1]
Должна запускаться задача статического анализа кода `./gradlew ktlint` на каждый PR

**Comment by JohnMars** [comment]
Давай возьмусь, как раз на работе тоже настраиваю 👍

**Comment by askarsyzdykov** [comment]
Отлично, спасибо!

**Comment by askarsyzdykov** [comment]
Добавил проверку на PR, если есть предложения по улучшению - welcome. 
https://github.com/sozdik-kz/sozdik-android/blob/develop/.github/workflows/lint.yml

Эту задачу закрою
