### ISSUE TITLE
Закрывать приложение только после двух нажатий на Back

### ISSUE THREAD

**Issue by askarsyzdykov** [sozdik-kz/sozdik-android#10]
Сейчас приложение закрывается после одного нажатия на Back и отображается тоаст "Нажмите еще раз для выхода".

Должно быть так:
1. Юзер находится на вкладке "Словарь" и нажимает Back
2. Программа показывает тоаст "Нажмите еще раз для выхода"
3. Юзер нажимает еще раз Back
4. Приложение закрывается

это сломалось после рефакторинга, смотреть метод `MainActivity::onBackPressed()`

**Comment by samatmeirbek** [comment]
Давай возьмусь за эту задачу, первый раз участвую на Hacktoberfest. Для меня это отличная возможность по практиковаться  🔥🚀
