### ISSUE TITLE
Спрятать кнопку Logout, если пользователь не авторизован

### ISSUE THREAD

**Issue by askarsyzdykov** [sozdik-kz/sozdik-android#3]
**Ожидаемый результат:**
Кнопка Logout должна отображаться только в случае, когда пользователь авторизован

**Фактический результат:**
![image](https://user-images.githubusercontent.com/3222305/93694938-8c103e00-fb33-11ea-9c3f-238c88d47579.png)

**Comment by wilko98** [comment]
Создал Пул риквест на эту задачу
